clone:
  git:
    image: bash
    settings:
      lfs: false

labels:
  backend: local

steps:
  - name: build-site
    image: node:lts
    commands:
      - node -v && npm -v
      - cd site
      - npm ci
      - npm run build

  - name: deploy-cloudflare
    image: node:lts
    depends_on:
      - build-site
    commands:
      - if [ -f /home/diama/.woodpecker-secrets/aeris-cf.env ]; then source /home/diama/.woodpecker-secrets/aeris-cf.env; fi
      - cd site
      - npx wrangler pages deploy dist --project-name=tsgate --branch=main --commit-dirty=true
    environment:
      CF_ACCOUNT_ID:
        from_secret: cf_account_id
      CF_API_TOKEN:
        from_secret: cf_api_token

when:
  event: [push, tag]
  branch: main
  ref: refs/tags/v*